pipeline {
  agent { label 'windows' }

  environment {
    PROJECTNAME = 'FileHashGenerator'
  }

  options {
    skipDefaultCheckout(true)
  }

  stages {
    stage('Cleanup Workspace') {
      steps {
        cleanWs()
      }
    }

    stage('Checkout GitHub') {
      steps {
        checkout scm
      }
    }

    stage('Build & Execute SonarQube analysis') {
      steps {
        withSonarQubeEnv('SonarQube') {
          bat "cd ./source && dotnet sonarscanner begin /k:${PROJECTNAME} /d:sonar.host.url=${env.SONAR_HOST_URL} /d:sonar.login=${env.SONAR_AUTH_TOKEN}"
          bat "cd ./source && nuget restore ${PROJECTNAME}.sln"
          bat "cd ./source && dotnet build"
          bat "cd ./source && dotnet test"
          bat "cd ./source && dotnet sonarscanner end /d:sonar.login=${env.SONAR_AUTH_TOKEN}"
        }
      }
    }
  }
}
